(function($){$.sticky=function(note,options,callback){return $.fn.sticky(note,options,callback)};$.fn.sticky=function(note,options,callback){var position='bottom-right';var settings={'speed':'slow','duplicates':!1,'autoclose':8000};if(!note){note=this.html()}
if(options){$.extend(settings,options)}
var display=!0;var duplicate='no';var uniqID=Math.floor(Math.random()*99999);$('.sticky-note').each(function(){if($(this).html()==note&&$(this).is(':visible')){duplicate='no';if(!settings.duplicates){display=!1}}
if($(this).attr('id')==uniqID){uniqID=Math.floor(Math.random()*9999999)}});if(!$('body').find('.sticky-queue').html()){$('body').append('<div class="sticky-queue '+position+'"></div>')}
if(display){$('.sticky-queue').prepend('<div class="sticky border-'+position+'" id="'+uniqID+'"></div>');$('#'+uniqID).append('<span class="sticky-close" rel="'+uniqID+'" title="Close" style="display: inline-block;float: right;cursor: pointer;">✖</span<>');$('#'+uniqID).append('<div class="sticky-note" rel="'+uniqID+'">'+note+'</div>');$('#'+uniqID).slideDown(settings.speed);display=!0}
$('.sticky').ready(function(){if(settings.autoclose){$('#'+uniqID).delay(settings.autoclose).fadeOut(settings.speed)}});$('.sticky-close').click(function(){$('#'+$(this).attr('rel')).dequeue().fadeOut(settings.speed)});var response={'id':uniqID,'duplicate':duplicate,'displayed':display,'position':position}
if(callback){callback(response)}else{return(response)}}})(jQuery);$(document).ready(function(){$.sticky('<b><img src="images/au.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.7 BTC <img src="images/coin.png" width="15" height="15"/></b>');var callnotification=function(){$.sticky('<b><img src="images/fr.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 1.3 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,20000);var callnotification=function(){$.sticky('<b><img src="images/ro.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.3 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,35000);var callnotification=function(){$.sticky('<b><img src="images/ch.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.1 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,70000);var callnotification=function(){$.sticky('<b><img src="images/ca.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.9 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,120000);var callnotification=function(){$.sticky('<b><img src="images/au.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 1.7 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,160000);var callnotification=function(){$.sticky('<b><img src="images/fr.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 1.1 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,190000);var callnotification=function(){$.sticky('<b><img src="images/in.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 1.57 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,220000);var callnotification=function(){$.sticky('<b><img src="images/in.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 1.9 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,250000);var callnotification=function(){$.sticky('<b><img src="images/it.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 2.1 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,290000);var callnotification=function(){$.sticky('<b><img src="images/us.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 2.2 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,300000);var callnotification=function(){$.sticky('<b><img src="images/ro.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 2.5 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,329000);var callnotification=function(){$.sticky('<b><img src="images/ca.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.25 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,351000);var callnotification=function(){$.sticky('<b><img src="images/be.png"/>  <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.35 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,385000);var callnotification=function(){$.sticky('<b><img src="images/ar.png"/>  <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.37 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,410000);var callnotification=function(){$.sticky('<b><img src="images/vi.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.27 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,450000);var callnotification=function(){$.sticky('<b><img src="images/ro.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.3 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,35800);var callnotification=function(){$.sticky('<b><img src="images/in.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.1 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,78000);var callnotification=function(){$.sticky('<b><img src="images/be.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.9 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,128000);var callnotification=function(){$.sticky('<b><img src="images/it.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 1.7 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,168000);var callnotification=function(){$.sticky('<b><img src="images/ch.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 1.1 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,198000);var callnotification=function(){$.sticky('<b><img src="images/au.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 1.57 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,228000);var callnotification=function(){$.sticky('<b><img src="images/ar.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 1.9 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,258800);var callnotification=function(){$.sticky('<b><img src="images/us.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 2.1 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,296800);var callnotification=function(){$.sticky('<b><img src="images/ch.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 2.2 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,388800);var callnotification=function(){$.sticky('<b><img src="images/be.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 2.5 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,328080);var callnotification=function(){$.sticky('<b><img src="images/us.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.25 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,358000);var callnotification=function(){$.sticky('<b><img src="images/au.png"/>  <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.35 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,388000);var callnotification=function(){$.sticky('<b><img src="images/ro.png"/>  <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.37 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,400000);var callnotification=function(){$.sticky('<b><img src="images/ch.png"/> <span style="font-weight: bold;"> '+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'.'+X00Random(1,255)+'</span> IP already received 0.27 BTC <img src="images/coin.png" width="15" height="15"/></b>')}
setInterval(callnotification,458000)})
